# Generated by Django 2.0 on 2018-01-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20171229_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt_name', models.CharField(max_length=100)),
                ('hotel_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Book',
            new_name='Hotel',
        ),
        migrations.DeleteModel(
            name='Writer',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='name_book',
            new_name='name_hotel',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='price_book',
            new_name='price_hotel',
        ),
    ]
